### ISSUE TITLE
running the basic example of ssh throws JSchException: failed to send channel request

### ISSUE THREAD

**Issue by yaochen** [dacr/jassh#15] opened 2015-08-04 18:37 UTC
Is this something on my end or something is wrong in the code?

ex:
```scala
import fr.janalyse.ssh._

val settings = SSHOptions(host = host, username=user, password = pass, prompt = Some(prompt), timeout = timeout)
val session = SSH(settings)

val shell = session.newPowerShell

println(shell.ls)
println(shell.pwd)
```

i was able to sftp into the host using command line.

**Comment by dacr** [comment] 2016-10-03 22:29
Can't reproduce. Do you confirm ? I'm closing the issue for the moment.

**Closed by dacr** 2016-10-03 22:29 UTC
